// GENERATED by src/ferramentas/gera_spots_interior.py from dados/b6-spots-angulos.json (or b6-inventario.json) — do not edit by hand.
// Source: MEDIDO pela B6 (dados/b6-spots-angulos.json): posicao SfM, direcao_uvh, aceso/apagado dos clipes
// [u, v, aim u, aim y, aim v] in the B4 plan frame (u 0 = kitchen wall), before mirroring.
export const FONTE_SPOTS = "MEDIDO pela B6 (dados/b6-spots-angulos.json): posicao SfM, direcao_uvh, aceso/apagado dos clipes";
export const SPOTS = [
  [3.9, 3.77, 3.105, 3.174, 2.711, 1, 2.47],
  [2.85, 3.77, 2.078, 1.968, 2.587, 0, 2.47],
  [1.85, 3.77, 1.814, 1.917, 5.163, 1, 2.47],
  [1.45, 4.2, 1.631, 1.839, 5.549, 0, 2.47],
  [1.45, 5.35, 1.675, 2.065, 6.776, 0, 2.47],
  [1.7, 5.65, 1.539, 2.118, 4.201, 0, 2.47],
  [2.85, 5.65, 1.871, 1.768, 4.756, 1, 2.47],
  [3.9, 5.65, 3.132, 2.166, 4.398, 1, 2.47],
  [4.4, 4.1, 3.259, 3.174, 3.429, 1, 2.47],
  [4.4, 5.3, 3.259, 3.174, 5.97, 1, 2.47],
];
